// * auth
export const STORAGE_KEY_AT = 'ECOMMERCE_ACCESS_TOKEN';
export const STORAGE_KEY_RT = 'ECOMMERCE_ACCESS_TOKEN_REFRESH_TOKEN';
export const STORAGE_USER_INFO = 'ECOMMERCE_ACCESS_TOKEN_USER_INFO';
export const IS_SERVER_TEST = true;